apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blazor-app
  template:
    metadata:
      labels:
        app: blazor-app
    spec:
      containers:
      - name: blazor-app
        image: thisisrasel/my-blazor-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blazor-app
spec:
  selector:
    app: blazor-app
  ports:
  - port: 8080
    targetPort: 80